### ISSUE TITLE
Restore previous T1 energy and metal storage capacity

### ISSUE THREAD

**Issue by Ca5an0va** [techannihilation/TA#266] opened 2017-05-26 20:37 UTC
New values (checked for CORE, but I guess is the same for ARM and TLL) are by far less balanced than previous ones.
Is it possible to consider the option to restore previous capacities?

Thank you

**Comment by Antarac** [comment] 2017-05-26 21:10
I like the new storages since it gives more relevancy to the storage system.
I think energy storage for example didn't change much since OTA so some
people are used to it since like 20 years and dont seem to like a change.

**Comment by nixtux** [comment] 2017-05-28 05:46
duplicate of https://github.com/techannihilation/TA/issues/265

**Closed by nixtux** 2017-05-28 05:46 UTC

**Comment by skymyj** [comment] 2017-05-31 13:55
I'm laughing. 
All parties I saw, with 6vs6 players, I only saw 2 or 3 energy storage (T1).
The metal storage ? why to make it ? Today, I make metal storage for defense... Metal extractor give 500m storage

The T2 energy storage ? Why to make one when I had 250++K Energy Storage given by 2 or 3 aafus or cafus. 

The T3 storage, when I saw one, it just made for no reason or just to try this unknown structure. (Cause 5+ afus made that give 60K*5 storage). 

So, when I saw PA players to complain, cause they don't want to micro their economy. Sorry but I'm laughing. 

We have an opportunity to develop the game with more sense and to differenciate with PA.
Only 'old porc eco' players will complain. And I'm not sure they will leave cause of these changes.

**Comment by nixtux** [comment] 2017-05-31 14:56
Hi sky
Starting any reply with "I'm laughing." means your here with the wrong attitude.

Those PA players that moaned where once TA players, the values in question have been in TA before even PA arrived. Im not say the changes was wrong but it the wrong time for such a big change.

Did you not read https://github.com/techannihilation/TA/issues/265#issuecomment-304494492

**Comment by skymyj** [comment] 2017-05-31 15:09
Yes I read this #265 
It's why I said PA players and porc Eco players.

And when will be the good time ?
