### ISSUE TITLE
Collision box to rework

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1178] opened 2018-06-02 08:17 UTC
![image](https://user-images.githubusercontent.com/2990630/40872417-252f222c-664e-11e8-97b4-1c98fe794294.png)
tllvp

Other structures coming

**Comment by skymyj** [comment] 2018-06-03 09:03
Same for tlleap

**Comment by nixtux** [comment] 2018-06-06 13:29
Duplicate of https://github.com/techannihilation/TA/issues/966
Closing issue

**Closed** 2018-06-25 07:48 UTC
